##
## EPITECH PROJECT, 2020
## Makfile
## File description:
## Makefile for project 103cipher
##

NAME	=	104intersection

all:
		cp main.py $(NAME)
		chmod +x $(NAME)

clean:
		$(RM) -r __pycache__

fclean:		clean
		$(RM) $(NAME)
		$(RM) -rf ./sources/__pycache__

re:		fclean all